language: node_js
node_js:
  - "12.13.0"
script:
  - echo "build react app..."
  - npm run build
  - echo "deploying..."
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project cbgroup-co-nz --token $FIREBASE_TOKEN
